name: nightly-tests
on: [push, pull_request]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy Models
        uses: actions/checkout@v2
        with:
          path: models
          persist-credentials: false

      - name: Run Tests
        run: |
          docker build . --file Dockerfile --tag trial
          docker run --rm -v `pwd`/models trial python3 -m pytest ivy_models_tests/
