name: nightly-tests
on: [push]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy Models
        uses: actions/checkout@v2
        with:
          path: models
          persist-credentials: false

      - name: Run Tests
        run: |
          docker run --rm -v `pwd`/models unifyai/models:latest python3 -m pytest ivy_models_tests/
